name: coopconnects
description: A cafeteria management app

# The version of your app, e.g., 1.0.0
version: 1.0.0+1

# SDK version constraint
environment:
  sdk: ">=3.0.0 <4.0.0"

# Define your dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  font_awesome_flutter: ^10.8.0

  # Firebase dependencies
  firebase_core: ^3.8.0             # Initialize Firebase
  firebase_auth: ^5.3.3             # Authentication services
  firebase_database: ^11.1.6        # Realtime Database
  cloud_firestore: ^5.5.0           # Firestore database
  firebase_messaging: ^15.1.5       # Push notifications

  # Google and Facebook sign-in
  google_sign_in: ^6.2.2            # Google sign-in
  flutter_facebook_auth: ^7.1.1     # Facebook sign-in

  # State management
  provider: ^6.1.2                  # State management with Provider

  # Local notifications and UI enhancements
  flutter_local_notifications: ^18.0.1 # Local notifications
  flutter_staggered_grid_view: ^0.7.0  # Staggered grid layout

  # Image caching and internationalization
  cached_network_image: ^3.4.1       # Caches images from the network
  intl: ^0.19.0                      # Internationalization

  # Form handling and validation
  flutter_form_builder: ^9.5.0       # For building forms

  # Splash screen package
  flutter_native_splash: ^2.4.3      # Native splash screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting for code quality
  flutter_lints: ^5.0.0

# Flutter configuration
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.gif           # Ensure these images exist in the specified paths

# Native splash screen configuration (outside dependencies)
flutter_native_splash:
  color: "#800000"                     # Deep Red Background color
  image: assets/images/logo.png        # Logo image for the splash screen
  android: true                        # Enable for Android
  ios: true                            # Enable for iOS
